spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: Week1Assignment
server:
  port: 9001
  
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG